---
title: "4.2 Exercise R Plots"
author: "Gabriel Valenzuela"
date: "7/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Plots

```{r echo = FALSE}
suppressWarnings(library(ggplot2))
suppressWarnings(library(hexbin))
suppressWarnings(library(dplyr))
suppressWarnings(library(gapminder))
suppressWarnings(library(ggmap))
suppressWarnings(library(maps))
suppressWarnings(library(mapdata))
suppressWarnings(library(plot3D))
suppressWarnings(library(plotly))

# import data

nba <- read.csv('ppg2008.csv')
head(nba)

costco <- read.csv('costcos-geocoded.csv')
head(costco)
```

# Heat Map
```{r echo=FALSE}
select(nba, -1)
#nba <- as.numeric(nba)
nba_matrix <- data.matrix(nba)
heatmap(nba_matrix, Colv = NA, Rowv = NA, scale='column',xlab="Stats", ylab="Values", main="NBA Stats of 2008 Season")
```

# Spatial Plot
```{r echo=FALSE}
#bc_bbox <- ggmap::make_bbox(lat = max(costco$Latitude), lon = max(costco$Longitude), data = costco)
```

# Contour Plot
```{r echo=FALSE}
x=nba$PTS
y=nba$MIN
z=nba$AST
df <- data.frame(x=x,y=y,z=z)
p <- plotly::plot_ly(data = df, x=~x,y=~y, z=~z, type = "contour", colorscale='Jet')
p
```


